const constants = {
  REGIONS_FETCH: 'REGIONS_FETCH',
  REGION_ADD: 'REGION_ADD',
  REGION_DELETE: 'REGION_DELETE',
  REGION_EDIT: 'REGION_EDIT',
  VENUES_FETCH: 'VENUES_FETCH',
  VENUE_ADD: 'VENUE_ADD',
  VENUE_DELETE: 'VENUE_DELETE',
  VENUE_EDIT: 'VENUE_EDIT',
  VENUE_FETCH_GOOGLE_PLACES_DETAIL: 'VENUE_FETCH_GOOGLE_PLACES_DETAIL',
  VENUE_FETCH_GOOGLE_PLACES_DETAIL_CANCEL: 'VENUE_FETCH_GOOGLE_PLACES_DETAIL_CANCEL',
  EDIT_VENUE_FETCH_GOOGLE_PLACES_DETAIL: 'EDIT_VENUE_FETCH_GOOGLE_PLACES_DETAIL',
  EDIT_VENUE_FETCH_GOOGLE_PLACES_DETAIL_CANCEL: 'EDIT_VENUE_FETCH_GOOGLE_PLACES_DETAIL_CANCEL',
  EDIT_VENUE_FETCH_YELP_PHONE_SEARCH_DETAIL: 'EDIT_VENUE_FETCH_YELP_PHONE_SEARCH_DETAIL',
  UI_VENUE_OPEN: 'UI_VENUE_OPEN',
  UI_SET_REGION: 'UI_SET_REGION',
  UI_VENUE_HOVER_ON: 'UI_VENUE_HOVER_ON',
  UI_VENUE_HOVER_OFF: 'UI_VENUE_HOVER_OFF',
  API_ERROR: 'API_ERROR'
}

export default constants
