const constants = {
  REGIONS_FETCH: 'REGIONS_FETCH',
  REGION_ADD: 'REGION_ADD',
  REGION_DELETE: 'REGION_DELETE',
  REGION_EDIT: 'REGION_EDIT',
  VENUES_FETCH: 'VENUES_FETCH',
  VENUE_FETCH_DETAIL: 'VENUE_FETCH_DETAIL',
  VENUE_FETCH_DETAIL_CANCEL: 'VENUE_FETCH_DETAIL_CANCEL',
  UI_VENUE_OPEN: 'UI_VENUE_OPEN',
  UI_SET_REGION: 'UI_SET_REGION',
  UI_VENUE_HOVER_ON: 'UI_VENUE_HOVER_ON',
  UI_VENUE_HOVER_OFF: 'UI_VENUE_HOVER_OFF',
  API_ERROR: 'API_ERROR'
}

export default constants
