const constants = {
  REGIONS_FETCH: 'REGIONS_FETCH',
  VENUES_FETCH: 'VENUES_FETCH',
  UI_VENUE_OPEN: 'UI_VENUE_OPEN',
  UI_SET_REGION: 'UI_SET_REGION',
  UI_VENUE_HOVER_ON: 'UI_VENUE_HOVER_ON',
  UI_VENUE_HOVER_OFF: 'UI_VENUE_HOVER_OFF'
}

export default constants
